### ISSUE TITLE
Error pytz library

### ISSUE THREAD

**Issue by micheleg95** [tim-hub/sanic-currency-exchange-rates-api#16]
[2021-08-29 02:52:32 +0200] [445596] [INFO] Goin' Fast @ http://0.0.0.0:8000
set up db
set up db
[2021-08-29 02:52:33 +0200] [445599] [INFO] Starting worker [445599]
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/lemonz/.local/lib/python3.8/site-packages/sanic/server.py", line 892, in serve
    trigger_events(before_start, loop)
  File "/home/lemonz/.local/lib/python3.8/site-packages/sanic/server.py", line 668, in trigger_events
    loop.run_until_complete(result)
  File "uvloop/loop.pyx", line 1501, in uvloop.loop.Loop.run_until_complete
  File "main.py", line 221, in initialize_scheduler
    scheduler.add_job(update_rates, "interval", hours=1)
  File "/home/lemonz/.local/lib/python3.8/site-packages/apscheduler/schedulers/base.py", line 420, in add_job
    'trigger': self._create_trigger(trigger, trigger_args),
  File "/home/lemonz/.local/lib/python3.8/site-packages/apscheduler/schedulers/base.py", line 921, in _create_trigger
    return self._create_plugin_instance('trigger', trigger, trigger_args)
  File "/home/lemonz/.local/lib/python3.8/site-packages/apscheduler/schedulers/base.py", line 906, in _create_plugin_instance
    return plugin_cls(**constructor_kwargs)
  File "/home/lemonz/.local/lib/python3.8/site-packages/apscheduler/triggers/interval.py", line 38, in __init__
    self.timezone = astimezone(timezone)
  File "/home/lemonz/.local/lib/python3.8/site-packages/apscheduler/util.py", line 93, in astimezone
    raise TypeError('Only timezones from the pytz library are supported')
TypeError: Only timezones from the pytz library are supported
/usr/lib/python3.8/multiprocessing/process.py:331: RuntimeWarning: coroutine 'Loop.create_server' was never awaited
  traceback.print_exc()
^C[2021-08-29 02:53:04 +0200] [445596] [INFO] Received signal SIGINT. Shutting down.
[2021-08-29 02:53:04 +0200] [445596] [INFO] Server Stopped
[2021-08-29 02:53:04 +0200] [445599] [INFO] Stopping worker [445599]

**Comment by micheleg95** [comment]
To resolve this, need to upgrade apscheduler package to latest version

**Comment by micheleg95** [comment]
I have created a PR for this

(the PR includes also update for gino package)

https://github.com/tim-hub/sanic-currency-exchange-rates-api/pull/17

**Comment by tim-hub** [comment]
PR merged

**Comment by tim-hub** [comment]
Hi @LemonzDEV 

Would you mind taking responsibility of maintaining the project? I would like to give you the mantainer permission if you are keen? :)
